theme: jekyll-theme-chirpy

lang: ko-KR
timezone: Asia/Seoul

title: "딥러닝_G24"
tagline: "Embedded Linux | HVAC | AI"

description: >
  Embedded Linux BSP,
  Device Driver,
  HVAC Controller,
  AI Project

url: "https://kkdeok87.github.io"
baseurl: ""

github:
  username: kkdeok87

social:
  name: "딥러닝_G24"

future: true
